name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x,15.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Start Redis
      uses: supercharge/redis-github-action@1.1.0
      with:
        redis-version: '5'
    - name: Setup Rabbitmq
      uses: nijel/rabbitmq-action@v1.0.0
    - name: Setup NATS
      run: |
        wget  https://github.com/nats-io/nats-server/releases/download/v2.0.0/nats-server-v2.0.0-linux-amd64.zip
        unzip nats-server-v2.0.0-linux-amd64.zip
        nats-server-v2.0.0-linux-amd64/nats-server </dev/null &>/dev/null &
    - run: sleep 30
    - run: npm ci
    - run: npm test
